development:
  adapter: postgresql
  encoding: unicode
  database: user_service_dev
  pool: 5
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: user_service_test
  pool: 5
  username: postgres
  password: postgres

production:
  adapter: postgresql
  encoding: unicode
  database: user_service_dev
  pool: 5
  username: postgres
  password: postgres